include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - always_use_package_imports
    - lines_longer_than_80_chars
    - prefer_const_constructors
    - prefer_double_quotes
    - prefer_expression_function_bodies
    - sort_constructors_first
    - sort_pub_dependencies
    - sort_unnamed_constructors_first