name: client
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^9.0.0
  desktop_multi_window: ^0.2.1
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  path_provider: ^2.1.5

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.6.0
  drift_dev: ^2.28.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
