FROM golang:alpine AS builder

WORKDIR /opt/config

COPY config/go.mod config/go.sum ./

RUN go mod download

COPY config/ .

RUN go build -o bin/config .

FROM alpine

COPY --from=builder /opt/config/bin/config/ bin/main

RUN chmod +x bin/main

CMD ["./bin/main"]
