FROM golang:alpine AS builder

WORKDIR /opt/api

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o bin/api cmd/api/main.go

FROM alpine

WORKDIR /opt/api

COPY --from=builder /opt/api/bin/api bin/api 
COPY --from=builder /opt/api/configuration.json configuration.json

RUN chmod +x bin/api

CMD ["./bin/api"]
