name: ephoros-server

services:
  db:
    image: timescale/timescaledb:latest-pg17
    env_file:
      - ../.env
    volumes:
      - ../.db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 1s
      retries: 20
  config:
    build:
      dockerfile: docker/Dockerfile.config
      context: ..
    env_file: ../.env
    depends_on:
      db:
        condition: service_healthy
  api:
    build:
      dockerfile: docker/Dockerfile.api
      context: ..
    env_file: ../.env
    depends_on:
      config:
        condition: service_completed_successfully
  mqtt_client:
    build:
      dockerfile: docker/Dockerfile.mqtt
      context: ..
    env_file: ../.env
    restart: unless-stopped
    depends_on:
      config:
        condition: service_completed_successfully
  broker:
    image: emqx/emqx-enterprise:5.10.0
    environment:
      - "EMQX_NODE_NAME=emqx@node1.emqx.com"
      - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
      - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.com,emqx@node2.emqx.com]"
    ports:
      - 18083:18083
