FROM golang:alpine AS builder

WORKDIR /opt/simulator

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o bin/simulator cmd/simulator/main.go

FROM alpine

WORKDIR /opt/simulator

COPY --from=builder /opt/simulator/bin/simulator bin/simulator 

RUN chmod +x bin/simulator

CMD ["./bin/simulator"]
