name: ephoros-server-test

services:
  db:
    image: timescale/timescaledb:latest-pg17
    env_file:
      - ../.env
    volumes:
      - ../.db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 1s
      retries: 20
  api:
    build:
      dockerfile: docker/Dockerfile.test
      context: ..
    env_file: ../.env
    depends_on:
      db:
        condition: service_healthy