name: ephoros-server

services:
  db:
    image: timescale/timescaledb:latest-pg17
    networks:
      - default
    env_file:
      - ../.env
    volumes:
      - ../.db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 1s
      retries: 20
  config:
    build:
      dockerfile: docker/Dockerfile.config
      context: ..
    networks:
      - default
    env_file: ../.env
    depends_on:
      db:
        condition: service_healthy
  api:
    build:
      dockerfile: docker/Dockerfile
      context: ..
      args:
        SERVICE: api
    networks:
      - default
    env_file: ../.env
    depends_on:
      config:
        condition: service_completed_successfully
      broker:
        condition: service_healthy
  saver:
    build:
      dockerfile: docker/Dockerfile
      context: ..
      args:
        SERVICE: saver
    networks:
      - default
    env_file: ../.env
    depends_on:
      config:
        condition: service_completed_successfully
      broker:
        condition: service_healthy
  processor:
    build:
      dockerfile: docker/Dockerfile
      context: ..
      args:
        SERVICE: processor
    networks:
      - default
    env_file: ../.env
    depends_on:
      config:
        condition: service_completed_successfully
      broker:
        condition: service_healthy
  simulator:
    build:
      dockerfile: docker/Dockerfile
      context: ..
      args:
        SERVICE: simulator
    networks:
      - default
    env_file: ../.env
    depends_on:
      config:
        condition: service_completed_successfully
      broker:
        condition: service_healthy
  broker:
    image: emqx/emqx-enterprise:5.10.0
    hostname: docker.emqx.com
    networks:
      default:
        aliases:
          - broker
    environment:
      - "EMQX_NODE_NAME=emqx@docker.emqx.com"
      - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
      - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@docker.emqx.com]"
      - "EMQX_HOST=docker.emqx.com"
    ports:
      - 18083:18083
      - 1883:1883
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  default:
    driver: bridge
