FROM golang:alpine AS builder

WORKDIR /opt/config

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o bin/config cmd/config/main.go

FROM alpine

WORKDIR /opt/config

COPY --from=builder /opt/config/bin/config bin/config 
COPY --from=builder /opt/config/configuration.json configuration.json

RUN chmod +x bin/config

CMD ["./bin/config"]
