name: ephoros-server-test

services:
  db:
    image: timescale/timescaledb:latest-pg17
    env_file:
      - ../.env
    volumes:
      - ../.db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 1s
      retries: 20
  api:
    image: cosmtrek/air
    working_dir: /app
    restart: unless-stopped
    env_file: ../.env
    entrypoint: ["/go/bin/air", "--build.cmd", "go test ./...", "--build.bin", "./bin/main"]
    volumes:
      - ../:/app